// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkAaazr6ztdu9VL7B8GZ5r7ONpk4esdTA',
    appId: '1:298313707801:web:c3e8a114f110cdd53b1588',
    messagingSenderId: '298313707801',
    projectId: 'newsapplication-2caa0',
    authDomain: 'newsapplication-2caa0.firebaseapp.com',
    storageBucket: 'newsapplication-2caa0.appspot.com',
    measurementId: 'G-7B35NPFLVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCf6VHk-fqLe1g1J3Vzc0Kmnhb7jIaBV0',
    appId: '1:298313707801:android:6daa8d9234d4513e3b1588',
    messagingSenderId: '298313707801',
    projectId: 'newsapplication-2caa0',
    storageBucket: 'newsapplication-2caa0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3v_w56Nrie0uu4C0Z0xNUFU-jAdHhGlM',
    appId: '1:298313707801:ios:4ff1140c234ad7c63b1588',
    messagingSenderId: '298313707801',
    projectId: 'newsapplication-2caa0',
    storageBucket: 'newsapplication-2caa0.appspot.com',
    iosClientId: '298313707801-bl9v9qnmcu31ma08n3arjua9rdj46dgn.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3v_w56Nrie0uu4C0Z0xNUFU-jAdHhGlM',
    appId: '1:298313707801:ios:4ff1140c234ad7c63b1588',
    messagingSenderId: '298313707801',
    projectId: 'newsapplication-2caa0',
    storageBucket: 'newsapplication-2caa0.appspot.com',
    iosClientId: '298313707801-bl9v9qnmcu31ma08n3arjua9rdj46dgn.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsapp',
  );
}
